cars = [
    {
        "id": 1,
        "modelo": "Fusca",
        "marca": "Volkswagen",
        "ano": 1972,
        "foto": "fusca.jpeg",
        "descricao": "Clássico da Volkswagen, o Fusca foi um dos carros mais populares do século 20, conhecido por sua durabilidade e design único.",
    },
    {
        "id": 2,
        "modelo": "Chevrolet Opala",
        "marca": "Chevrolet",
        "ano": 1979,
        "foto": "opala.jpeg",
        "descricao": "Um dos sedãs mais famosos do Brasil, o Opala combinava conforto e desempenho, sendo utilizado inclusive pela polícia e táxis.",
    },
    {
        "id": 3,
        "modelo": "Ford Maverick",
        "marca": "Ford",
        "ano": 1974,
        "foto": "maverick.jpeg",
        "descricao": "Muscle car da Ford que ganhou fãs por seu motor V8 potente e visual esportivo.",
    },
    {
        "id": 4,
        "modelo": "Chevrolet Bel Air",
        "marca": "Chevrolet",
        "ano": 1957,
        "foto": "bel_air.jpeg",
        "descricao": "Símbolo dos anos 50, o Bel Air é famoso por seu acabamento cromado e estilo elegante.",
    },
    {
        "id": 5,
        "modelo": "Volkswagen Kombi",
        "marca": "Volkswagen",
        "ano": 1965,
        "foto": "kombi.jpeg",
        "descricao": "Ícone da cultura hippie e do transporte coletivo, a Kombi foi um utilitário versátil por décadas.",
    },
    {
        "id": 6,
        "modelo": "Dodge Charger R/T",
        "marca": "Dodge",
        "ano": 1969,
        "foto": "charger.jpeg",
        "descricao": "Um dos muscle cars mais icônicos dos EUA, com grande presença em filmes e séries como 'Velozes e Furiosos'.",
    },
    {
        "id": 7,
        "modelo": "Puma GTE",
        "marca": "Puma",
        "ano": 1976,
        "foto": "puma.jpeg",
        "descricao": "Esportivo brasileiro feito sobre chassi de Fusca, famoso pelo design esportivo e artesanal.",
    },
    {
        "id": 8,
        "modelo": "Jeep Willys",
        "marca": "Willys-Overland",
        "ano": 1951,
        "foto": "willys_jeep.jpeg",
        "descricao": "Utilitário robusto usado na Segunda Guerra Mundial, depois adaptado para uso civil no Brasil e no mundo.",
    },
    {
        "id": 9,
        "modelo": "Citroën DS",
        "marca": "Citroën",
        "ano": 1967,
        "foto": "citroen-ds.jpeg",
        "descricao": "Revolucionário carro francês, famoso pela suspensão hidropneumática e design futurista.",
    },
    {
        "id": 10,
        "modelo": "Mini Cooper",
        "marca": "Austin",
        "ano": 1963,
        "foto": "mini-cooper.jpeg",
        "descricao": "Pequeno, ágil e com muito carisma, o Mini Cooper foi um sucesso nas corridas e nas ruas.",
    },
]
